sudo: false
language: java
jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - TERM=dumb

install:
  - ./gradlew --version

script:
  - ./gradlew -Dmaven.repo.local=cnf/cache/stable/m2 --continue

before_cache:
  - git status
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - cnf/cache/stable/
